[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist"
  environment = { DATABASE_URL = "", REPLIT_DOMAINS = "" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
node_bundler = "esbuild"
external_node_modules = [
  "@replit/vite-plugin-cartographer",
  "openid-client",
  "@babel/preset-typescript",
  "lightningcss"
]
